#!/bin/bash
git pull

# copy the source kernel 
cp host/ext4/*  ../linux/fs/ext4 -r
cp host/jbd2/*  ../linux/fs/jbd2 -r

# build the kernel
cd ../linux/
make CC="ccache gcc" -j12 && \
sudo make CC="ccache gcc" modules_install -j12 && \
sudo make CC="ccache gcc" install -j12 && \

sudo rm /boot/*4.19* -f && \
sudo update-grub2 && \
# reboot the system
sudo reboot
